Components become optional
Project-Counter/cop5 pull request #167
Opened 2023-03-14 11:57 UTC by tashalouizamc

Specifying that provision of component usage reports is at the discretion of report providers

2023-03-14 23:38 UTC, berndoberknapp commented on source/03-specifications/03-counter-report-common-attributes-and-elements.rst
> +     - Specifies whether to include the parent columns/elements (see Table 3.j) in the report, where report providers offer component usage reporting. Permissible values are False (default) and True.
Parents are not related to components, so this change must be reverted.

2023-03-14 23:41 UTC, berndoberknapp commented on source/04-reports/04-item-reports.rst
> +The following elements MUST appear in the tabular report in the order they appear in the table below. For guidance on how these elements appear in the JSON format, refer to the COUNTER_SUSHI API Spec
Parent reporting is required. I would suggest to split this sentence into two sentences, one for parent and one for component reporting.

2023-03-14 23:49 UTC, berndoberknapp commented on source/appendices/f-handling-errors-and-exceptions.rst
> +     - The request contained Component attribute values that are not supported by the server. The server should list the names of unsupported report attribute values in the additional Data element.
The component elements cannot be requested individually. Suggestion: The request contained include_component_details=True, but reporting on component usage is not supported.

2023-03-14 23:49 UTC, berndoberknapp requested changes
Please see the inline comments.

2023-03-15 13:39 UTC, tashalouizamc commented
Comments addressed in new commit 2023-03-15

2023-03-16 20:38 UTC, berndoberknapp approved these changes

2023-03-16 20:46 UTC, merged