Access_Type definitions
Project-Counter/cop5 pull request #172
Opened 2023-03-14 17:24 UTC by tashalouizamc

Updated the access_type definitions, use of access_types throughout the cop, and the terminology around standard view names

2023-03-14 22:33 UTC, berndoberknapp commented on source/03-specifications/03-counter-report-common-attributes-and-elements.rst
> +* Open was previously known as OA_Gold.
This seems misleading to me - OA_Gold is covered by Gold, but Gold includes much more than just OA_Gold.

The paragraph above the note still lists the old Access_Types. If we want to keep that, I would suggest to add the note about the changes after that sentence, and then start a new paragraph with "The table below...".

2023-03-14 22:34 UTC, berndoberknapp commented on source/appendices/a-glossary-of-terms.rst
> +     - A COUNTER Access_Type, previously known as OA_Gold. At the time of the Request or Investigation the content item was available to all users on this platform, regardless of authorization status
As mentioned above the "previously known as OA_Gold" seems misleading to me.

2023-03-14 22:51 UTC, berndoberknapp requested changes
There is a number of places where OA_Gold is still used (besides appendices which will be replaced): Section 1.2.4, caption for Figure 3.b (maybe covered by #165), above Table 3.s, Section 8.1 and Section 11.1.

The Host_Types and Reports in Table 3.u need to be updated for Free_To_Read. I assume Open (and OA_Gold in 5.0?) also would apply to eBook_Collection which is required to provide TR?

2023-03-15 14:16 UTC, tashalouizamc commented
New commit to address comments, 2023-03-15

2023-03-16 22:06 UTC, berndoberknapp commented on source/appendices/a-glossary-of-terms.rst
> +     - See Open.
Open on longer contains a reference to OA_Gold, so maybe the change should be explained here?

2023-03-16 22:06 UTC, berndoberknapp commented on source/appendices/a-glossary-of-terms.rst
> +     - See Free_To_Read.
Free_To_Read on longer contains a reference to Other_Free_To_Read, so maybe the change should be explained here?

2023-03-16 22:09 UTC, berndoberknapp requested changes
The Host_Types and Reports in Table 3.u still need to be updated for Free_To_Read.

I assume Open (and OA_Gold in 5.0?) also would apply to eBook_Collection which is required to provide TR?

2023-03-17 08:10 UTC, tashalouizamc commented
> The Host_Types and Reports in Table 3.u still need to be updated for Free_To_Read.
> 
> I assume Open (and OA_Gold in 5.0?) also would apply to eBook_Collection which is required to provide TR?

I left this one the other day because I was still pondering it, but I wonder why the access types need to be restricted at all - shouldn't they be for all host types?

2023-03-17 22:44 UTC, berndoberknapp commented
> I left this one the other day because I was still pondering it, but I wonder why the access types need to be restricted at all - shouldn't they be for all host types?

The Access_Types indeed don't have to be restricted, but the tables only show what is required. Since Access_Type is only applicable for TR and IR, only the Host_Types required to provide TR or IR are listed. I've adapted the Host_Types accordingly and fixed the Reports for Free_To_Read.

2023-03-17 23:09 UTC, berndoberknapp approved these changes
The text in Section 3.3.5 was changed both in #171 and this pull request. I've kept the version from #171, but included the note from this pull request.

2023-03-17 23:13 UTC, merged