Book_Segment extension
Project-Counter/cop5 pull request #175
Opened 2023-03-15 16:16 UTC by tashalouizamc

Added Book_Segment_Count to the list of reserved extensions

2023-03-16 22:19 UTC, berndoberknapp commented on source/11-extending/05-reserved-values-available-for-extending-reports.rst
> +     - PR, DR, TR
PR and DR seem wrong to me, since the number of Book_Segments can only be specified on the title level.

2023-03-16 22:52 UTC, berndoberknapp requested changes
Please see the inline comment.

2023-03-17 08:12 UTC, tashalouizamc commented on source/11-extending/05-reserved-values-available-for-extending-reports.rst
> +     - PR, DR, TR
change made

2023-03-17 21:41 UTC, berndoberknapp approved these changes

2023-03-17 21:47 UTC, merged