Images issue165
Project-Counter/cop5 pull request #191
Opened 2023-03-19 14:58 UTC by tashalouizamc

Replaced images 3a to 3e, including updating figure labels and alt-text where necessary. Deleted defunct images for audit logo and tech notes.

2023-03-19 21:55 UTC, berndoberknapp requested changes
You've removed the 91-counter-audit-logo.jpg and d-tech-notes-cover.jpg, but not the corresponding references?

2023-03-20 10:10 UTC, tashalouizamc commented
> You've removed the 91-counter-audit-logo.jpg and d-tech-notes-cover.jpg, but not the corresponding references?

As far as I know, the audit logo is only referenced in the R5 version of section 9, which is replaced by pr #185 and the tech notes cover is only in section d, which is being deleted as part of the clean up issue

2023-03-24 09:51 UTC, merged

2023-03-24 09:51 UTC, tashalouizamc commented
Merging to facilitate clean up and text edit issues

2023-03-26 19:47 UTC, berndoberknapp commented on source/03-specifications/01-counter-reports-for-consumers.rst
> +.. figure:: ../_static/img/Figure-3a.png
The option to include the "called for" columns Access_Type, Access_Method and YOP in the report is missing in the new image (Data_Type is now required, and the checkbox for Metric_Type was wrong in the old image).

2023-03-26 19:55 UTC, berndoberknapp commented on source/03-specifications/02-formats-for-counter-reports.rst
> +.. figure:: ../_static/img/Figure-3b.png
The Title Report needs to be scaled down a lot to fit on the page and is therefore difficult to read. I would suggest to only use the left half of the current images (with the fixes below).

The Release must be formatted as string. The Metric_Types filter is the default, therefore the list must be omitted. Attributes_To_Show is missing.

2023-03-26 20:08 UTC, berndoberknapp commented on source/03-specifications/02-formats-for-counter-reports.rst
> +.. figure:: ../_static/img/Figure-3c.png
Please replace "Report / Item" (I have no idea why that term was used in the old image) with "Report Attributes". The singular/plural should be consistent (e.g. Metric types but Reporting period total). I would prefer the same upper/lower case as in the text, e.g. Metric Types.

2023-03-26 20:10 UTC, berndoberknapp commented on source/03-specifications/02-formats-for-counter-reports.rst
> +.. figure:: ../_static/img/Figure-3c.png
I forgot to mention that I would prefer vertical dotted line between the areas as in the old image.

2023-03-26 20:23 UTC, berndoberknapp commented on source/03-specifications/03-counter-report-common-attributes-and-elements.rst
> +.. figure:: ../_static/img/Figure-3e.png
I find the Investigations part in the old image easier to understand, especially:

- The terms are ambiguous without the "user action" part. Only a user action that results for example in a metdata record to be shown is an Investigation, but not a metadata record for example shown in a result list.
- The outgoing link actions are missing. In my opinion these are important examples that are not obvious.

2023-03-26 20:24 UTC, berndoberknapp reviewed
Please see the inline comments.