First tranche of clean up
Project-Counter/cop5 pull request #195
Opened 2023-04-02 14:23 UTC by tashalouizamc

First set of clean up work. 

Revised images are yet to be drafted.

Much of the other unresolved clean up content is covered in the general editing issue

2023-04-11 10:41 UTC, berndoberknapp commented on source/04-reports/03-title-reports.rst
>         Access_Method=Regular*
The filters (e.g. Data_Type and Access_Type) are separated by semicolon-space, but the values within a filter must be separated by the pipe character, so the old version was correct.

2023-04-11 10:46 UTC, berndoberknapp commented on source/06-logging/01-log-file-analysis.rst
> +Report providers wishing to learn more about log files should read the `Amazon Web Service documentation <https://docs.aws.amazon.com>`.
Underscore missing (previous pull request was correct).

2023-04-11 10:47 UTC, berndoberknapp commented on source/07-processing/07-federated-searches.rst
> +* All searches via APIs and `Z39.50 <http://www.niso.org/standards/resources/Z39.50_Resources>` activity must be counted as Searches_Federated, as the results are not presented in the platform user i
Same here and for many other links in this pull request.

2023-04-11 10:48 UTC, berndoberknapp commented on source/08-sushi/index.rst
> +`<https://app.swaggerhub.com/apis/COUNTER/counter-sushi_5_0_api/>`
I would suggest to also use that URL as text (so that the URL is shown). Underscore is missing.

2023-04-11 10:55 UTC, berndoberknapp commented on source/13-transitioning/02-transitioning-to-a-new-code-of-practice.rst
> +* Are not required to meet the requirement to offer valid COUNTER reports for the current year plus the prior 24 months, but may choose to do so at their discretion.
Based on our discussion in the EC meeting: Add that the report provider is not required to provide reports according to the current release (which is still effective) for compliance?

2023-04-11 11:02 UTC, berndoberknapp commented on source/appendices/d-guidelines-for-implementation.rst
This requires changing the titles of and all references to Appendices E-I.

2023-04-11 11:08 UTC, berndoberknapp commented on source/_static/img/Figure 3a.png
The new figures have a space instead of a hypen in the name, but the references haven't been changed, therefore the old figures are still used.

2023-04-11 11:10 UTC, berndoberknapp commented on source/_static/img/Figure 3c.png
Please remove the / from "Report / Attributes". Attributes maybe should be lower case?

2023-04-11 11:12 UTC, berndoberknapp requested changes
Please see the inline comments. Most links probably will be corrected by resolving the conflicts with the text edits pull request and keeping the links from that pull request.

2023-04-11 14:59 UTC, tashalouizamc commented on source/06-logging/01-log-file-analysis.rst
> +Report providers wishing to learn more about log files should read the `Amazon Web Service documentation <https://docs.aws.amazon.com>`.
I think I've fixed this in the text updates pull

2023-04-11 14:59 UTC, tashalouizamc commented on source/07-processing/07-federated-searches.rst
> +* All searches via APIs and `Z39.50 <http://www.niso.org/standards/resources/Z39.50_Resources>` activity must be counted as Searches_Federated, as the results are not presented in the platform user i
as above

2023-04-11 23:30 UTC, berndoberknapp commented on source/13-transitioning/02-transitioning-to-a-new-code-of-practice.rst
> +Report providers implementing COUNTER for the first time are encouraged to contact the COUNTER Project Director (tasha.mellins-cohen@counterusage.org) for advice and support and to request inclusion
The reference to Section 10 seems wrong to me, it probably should point to Section 9.5?

2023-04-11 23:43 UTC, berndoberknapp commented on source/13-transitioning/02-transitioning-to-a-new-code-of-practice.rst
> +Report providers implementing COUNTER for the first time are encouraged to contact the COUNTER Project Director (tasha.mellins-cohen@counterusage.org) for advice and support and to request inclusion
The reference to Section 10 seems wrong to me, it probably should point to Section 9.5?

2023-04-11 23:53 UTC, berndoberknapp commented on source/_static/img/Figure-3b.png
The Report_Attributes are wrong - Data_Type is mandatory and therefore cannot be called for via Attributes_To_Show. Note that if still all Metric_Type are listed (which is not clear since they are cut off) this would be wrong - this would be the default which would have to be omitted.

2023-04-11 23:55 UTC, berndoberknapp approved these changes

2023-04-11 23:56 UTC, berndoberknapp commented
There are still some issues (please see the remaining comments), but they can be addressed in a separate pull request.

2023-04-12 00:04 UTC, berndoberknapp commented on source/09-audit/01-the-audit-process.rst
> +* **Stage five**-  audit complete. Once a Pass Report is issued, COUNTER will update the Registry of COUNTER compliant platforms to reflect the updated audit status of all platforms covered by the au
Space missing before -.

2023-04-12 00:11 UTC, merged